// cardsImages.js

// Create a function that dynamically imports the images from the new path
export const getImageById = async (id) => {
    const imageMap = {
        1: () => import('./assets/Cards/011.jpg'),
        2: () => import('./assets/Cards/012.jpg'),
        3: () => import('./assets/Cards/013.jpg'),
        4: () => import('./assets/Cards/014.jpg'),
        5: () => import('./assets/Cards/021.jpg'),
        6: () => import('./assets/Cards/022.jpg'),
        7: () => import('./assets/Cards/023.jpg'),
        8: () => import('./assets/Cards/024.jpg'),
        9: () => import('./assets/Cards/031.jpg'),
        10: () => import('./assets/Cards/032.jpg'),
        11: () => import('./assets/Cards/033.jpg'),
        12: () => import('./assets/Cards/034.jpg'),
        13: () => import('./assets/Cards/041.jpg'),
        14: () => import('./assets/Cards/042.jpg'),
        15: () => import('./assets/Cards/043.jpg'),
        16: () => import('./assets/Cards/044.jpg'),
        17: () => import('./assets/Cards/051.jpg'),
        18: () => import('./assets/Cards/052.jpg'),
        19: () => import('./assets/Cards/053.jpg'),
        20: () => import('./assets/Cards/054.jpg'),
        21: () => import('./assets/Cards/061.jpg'),
        22: () => import('./assets/Cards/062.jpg'),
        23: () => import('./assets/Cards/063.jpg'),
        24: () => import('./assets/Cards/064.jpg'),
        25: () => import('./assets/Cards/071.jpg'),
        26: () => import('./assets/Cards/072.jpg'),
        27: () => import('./assets/Cards/073.jpg'),
        28: () => import('./assets/Cards/074.jpg'),
        29: () => import('./assets/Cards/081.jpg'),
        30: () => import('./assets/Cards/082.jpg'),
        31: () => import('./assets/Cards/083.jpg'),
        32: () => import('./assets/Cards/084.jpg'),
        33: () => import('./assets/Cards/091.jpg'),
        34: () => import('./assets/Cards/092.jpg'),
        35: () => import('./assets/Cards/093.jpg'),
        36: () => import('./assets/Cards/094.jpg'),
        37: () => import('./assets/Cards/101.jpg'),
        38: () => import('./assets/Cards/102.jpg'),
        39: () => import('./assets/Cards/103.jpg'),
        40: () => import('./assets/Cards/104.jpg'),
        41: () => import('./assets/Cards/111.jpg'),
        42: () => import('./assets/Cards/112.jpg'),
        43: () => import('./assets/Cards/113.jpg'),
        44: () => import('./assets/Cards/114.jpg'),
        45: () => import('./assets/Cards/121.jpg'),
        46: () => import('./assets/Cards/122.jpg'),
        47: () => import('./assets/Cards/123.jpg'),
        48: () => import('./assets/Cards/124.jpg'),
    };

    // Return the image import promise based on the id
    return imageMap[id] ? imageMap[id]() : null;
};
