// cardsImages.js

// Create a function that dynamically imports the images from the new path
export const getImageById = async (id) => {
    const imageMap = {
        1: () => import('./assets/Cards/011.png'),
        2: () => import('./assets/Cards/012.png'),
        3: () => import('./assets/Cards/013.png'),
        4: () => import('./assets/Cards/014.png'),
        5: () => import('./assets/Cards/021.png'),
        6: () => import('./assets/Cards/022.png'),
        7: () => import('./assets/Cards/023.png'),
        8: () => import('./assets/Cards/024.png'),
        9: () => import('./assets/Cards/031.png'),
        10: () => import('./assets/Cards/032.png'),
        11: () => import('./assets/Cards/033.png'),
        12: () => import('./assets/Cards/034.png'),
        13: () => import('./assets/Cards/041.png'),
        14: () => import('./assets/Cards/042.png'),
        15: () => import('./assets/Cards/043.png'),
        16: () => import('./assets/Cards/044.png'),
        17: () => import('./assets/Cards/051.png'),
        18: () => import('./assets/Cards/052.png'),
        19: () => import('./assets/Cards/053.png'),
        20: () => import('./assets/Cards/054.png'),
        21: () => import('./assets/Cards/061.png'),
        22: () => import('./assets/Cards/062.png'),
        23: () => import('./assets/Cards/063.png'),
        24: () => import('./assets/Cards/064.png'),
        25: () => import('./assets/Cards/071.png'),
        26: () => import('./assets/Cards/072.png'),
        27: () => import('./assets/Cards/073.png'),
        28: () => import('./assets/Cards/074.png'),
        29: () => import('./assets/Cards/081.png'),
        30: () => import('./assets/Cards/082.png'),
        31: () => import('./assets/Cards/083.png'),
        32: () => import('./assets/Cards/084.png'),
        33: () => import('./assets/Cards/091.png'),
        34: () => import('./assets/Cards/092.png'),
        35: () => import('./assets/Cards/093.png'),
        36: () => import('./assets/Cards/094.png'),
        37: () => import('./assets/Cards/101.png'),
        38: () => import('./assets/Cards/102.png'),
        39: () => import('./assets/Cards/103.png'),
        40: () => import('./assets/Cards/104.png'),
        41: () => import('./assets/Cards/111.png'),
        42: () => import('./assets/Cards/112.png'),
        43: () => import('./assets/Cards/113.png'),
        44: () => import('./assets/Cards/114.png'),
        45: () => import('./assets/Cards/121.png'),
        46: () => import('./assets/Cards/122.png'),
        47: () => import('./assets/Cards/123.png'),
        48: () => import('./assets/Cards/124.png'),
    };

    // Return the image import promise based on the id
    return imageMap[id] ? imageMap[id]() : null;
};
